name: client_kill_switch_api
description: A small REST Api that works as a kill-switch for software demos
version: 0.0.1
repository: https://github.com/MrR-Py/client-kill-switch-api

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  mongo_dart: ^0.9.1

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
